// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// read_data
RcppExport SEXP read_data(Rcpp::String stringname, std::string fillMiss);
RcppExport SEXP _XPASS_read_data(SEXP stringnameSEXP, SEXP fillMissSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type stringname(stringnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type fillMiss(fillMissSEXP);
    rcpp_result_gen = Rcpp::wrap(read_data(stringname, fillMiss));
    return rcpp_result_gen;
END_RCPP
}
// scaleC
RcppExport SEXP scaleC(arma::mat X);
RcppExport SEXP _XPASS_scaleC(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleC(X));
    return rcpp_result_gen;
END_RCPP
}
// scaleC_ref
RcppExport SEXP scaleC_ref(arma::mat& X);
RcppExport SEXP _XPASS_scaleC_ref(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleC_ref(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_XPASS_read_data", (DL_FUNC) &_XPASS_read_data, 2},
    {"_XPASS_scaleC", (DL_FUNC) &_XPASS_scaleC, 1},
    {"_XPASS_scaleC_ref", (DL_FUNC) &_XPASS_scaleC_ref, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_XPASS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
