# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_data <- function(stringname, fillMiss = "none") {
    .Call(`_XPASS_read_data`, stringname, fillMiss)
}

scaleC <- function(X) {
    .Call(`_XPASS_scaleC`, X)
}

scaleC_ref <- function(X) {
    .Call(`_XPASS_scaleC_ref`, X)
}

